src/main/java/org/sonarsource/sonarlint/ls/connected/ProjectBindingManager.java, src/test/java/org/sonarsource/sonarlint/ls/connected/ProjectBindingManagerTests.java
I tested the previous version (from the dogfood channel) with bad server credentials and did not see the error popup. Upon inspection of the console output, I saw that the command execution failed, due to an uncaught exception in the individual folder binding updates.
=> SLVSCODE-119 Also catch error on update of individual folder bindings

src/main/java/org/sonarsource/sonarlint/ls/AnalysisManager.java, src/main/java/org/sonarsource/sonarlint/ls/CommandManager.java, src/main/java/org/sonarsource/sonarlint/ls/commands/ShowAllLocationsCommand.java, src/main/java/org/sonarsource/sonarlint/ls/commands/package-info.java, src/test/java/org/sonarsource/sonarlint/ls/CommandManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/commands/ShowAllLocationsCommandTest.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/JavaMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java
* Add cache of issues to keep location data for generation of code actions
* Add code action to send secondary locations to a client command
=> SLLS-20 Show secondary locations of local issues

README.md
Update of Azure DevOps URL after changing settings in AZP.
=> Update AZP URL in readme.md

src/main/java/org/sonarsource/sonarlint/ls/AnalysisManager.java, src/main/java/org/sonarsource/sonarlint/ls/CommandManager.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintTelemetry.java, src/main/java/org/sonarsource/sonarlint/ls/TelemetryClientAttributesProviderImpl.java, src/main/java/org/sonarsource/sonarlint/ls/connected/SecurityHotspotsHandlerServer.java, src/main/java/org/sonarsource/sonarlint/ls/standalone/StandaloneEngineManager.java, src/main/java/org/sonarsource/sonarlint/ls/standalone/package-info.java, src/test/java/org/sonarsource/sonarlint/ls/AnalysisManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/CommandManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/SonarLintTelemetryTests.java, src/test/java/org/sonarsource/sonarlint/ls/TelemetryClientAttributesProviderImplTest.java, src/test/java/org/sonarsource/sonarlint/ls/connected/SecurityHotspotsHandlerServerTest.java
This is a draft. Tests are missing!
=> SLLS-37 Rules telemetry

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/AnalysisManager.java, src/main/java/org/sonarsource/sonarlint/ls/ScmIgnoredCache.java, src/main/java/org/sonarsource/sonarlint/ls/TelemetryClientAttributesProviderImpl.java, src/main/java/org/sonarsource/sonarlint/ls/connected/DelegatingIssue.java, src/main/java/org/sonarsource/sonarlint/ls/http/ApacheHttpClient.java, src/main/java/org/sonarsource/sonarlint/ls/http/ApacheHttpResponse.java, src/main/java/org/sonarsource/sonarlint/ls/java/JavaConfigCache.java
I adapted HTTP client implementation from SLI, so maybe @damien-urruty-sonarsource you might be interested to give a look?
=> Update core library to 6.4

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/NodeJsRuntime.java, src/main/java/org/sonarsource/sonarlint/ls/connected/ProjectBindingManager.java, src/main/java/org/sonarsource/sonarlint/ls/connected/ProjectBindingWrapper.java, src/main/java/org/sonarsource/sonarlint/ls/folders/WorkspaceFolderWrapper.java, src/main/java/org/sonarsource/sonarlint/ls/java/JavaSdkUtil.java, src/main/java/org/sonarsource/sonarlint/ls/settings/ServerConnectionSettings.java, src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java, src/main/java/org/sonarsource/sonarlint/ls/settings/WorkspaceFolderSettings.java, src/main/java/org/sonarsource/sonarlint/ls/settings/WorkspaceSettings.java, src/test/java/org/sonarsource/sonarlint/ls/connected/ProjectBindingManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/folders/WorkspaceFoldersManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/settings/ServerConnectionSettingsTests.java, src/test/java/org/sonarsource/sonarlint/ls/settings/WorkspaceFolderSettingsTests.java, src/test/java/org/sonarsource/sonarlint/ls/settings/WorkspaceSettingsTests.java
ToStringBuilder now dump fields in alphabetic order.
=> Update Maven dependencies

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/http/ApacheHttpClientProvider.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/JavaMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java
This avoids an error trace that was fixed with CPP-3600
=> Stabilize tests

src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/connected/TaintIssuesUpdater.java, src/test/java/org/sonarsource/sonarlint/ls/connected/TaintIssuesUpdaterTests.java, src/test/java/testutils/ImmediateExecutorService.java
This prevents the LSP message processor from getting stuck
=> SLLS-93 Fetch taint issues asynchronously on file open

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/AnalysisTaskExecutor.java, src/main/java/org/sonarsource/sonarlint/ls/EnginesFactory.java, src/main/java/org/sonarsource/sonarlint/ls/notebooks/NotebookUtils.java, src/main/java/org/sonarsource/sonarlint/ls/notebooks/VersionedOpenNotebook.java, src/test/java/org/sonarsource/sonarlint/ls/AnalysisSchedulerTests.java, src/test/java/org/sonarsource/sonarlint/ls/CommandManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/EnginesFactoryTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/NotebookMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/notebooks/NotebookDiagnosticPublisherTests.java, src/test/java/org/sonarsource/sonarlint/ls/notebooks/NotebookUtilsTests.java, src/test/java/org/sonarsource/sonarlint/ls/notebooks/OpenNotebooksCacheTests.java, src/test/java/org/sonarsource/sonarlint/ls/notebooks/VersionedOpenNotebookTests.java
This PR relies on locally built sonar-python analyser (3.26-SNAPSHOT version). It shouldn't be merged until we will have a sonar-python analyser with new language support on repox.
=> SLLS-121 Treat Jupyter documents as being in IPython language

pom.xml
SLLS-136 update go analyzer used by tests to the latest released version 1.12.0.4259
=> SLLS-136 update go analyzer

.cirrus.yml
- BUILD-3317 fix cron
- BUILD-3317 Maven cache
- BUILD-3317 test cron
=> BUILD-3317 cron

src/main/java/org/sonarsource/sonarlint/ls/AnalysisScheduler.java, src/main/java/org/sonarsource/sonarlint/ls/AnalysisTaskExecutor.java, src/main/java/org/sonarsource/sonarlint/ls/ScmIgnoredCache.java, src/main/java/org/sonarsource/sonarlint/ls/connected/ProjectBindingManager.java, src/main/java/org/sonarsource/sonarlint/ls/file/OpenFilesCache.java, src/main/java/org/sonarsource/sonarlint/ls/java/JavaConfigCache.java, src/main/java/org/sonarsource/sonarlint/ls/notebooks/OpenNotebooksCache.java, src/test/java/org/sonarsource/sonarlint/ls/AnalysisSchedulerTests.java, src/test/java/org/sonarsource/sonarlint/ls/connected/ProjectBindingManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/connected/events/ServerSentEventsTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/JavaMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerWithFoldersMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/NotebookMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/notebooks/OpenNotebooksCacheTests.java
This is a rebased version of #273 to check if coverage is computed correctly on Next
=> SLLS-158 wrap file names in double quotes in logs

src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java
[SLLS-221](https://sonarsource.atlassian.net/browse/SLLS-221)
[SLLS-221]: https://sonarsource.atlassian.net/browse/SLLS-221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-221 make binding no-match error more helpful

src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/settings/SettingsManagerTests.java
[SLLS-259](https://sonarsource.atlassian.net/browse/SLLS-259)
[SLLS-259]: https://sonarsource.atlassian.net/browse/SLLS-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-259, SLLS-258 properly parse settings

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml
=> SLLS-264 Jira integration: Use repo vault token

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java, src/main/java/org/sonarsource/sonarlint/ls/util/EnumLabelsMapper.java, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java, src/test/java/org/sonarsource/sonarlint/ls/util/EnumLabelsMapperTests.java
=> SLLS-263 Adopt INFO and BLOCKER impact severity levels

src/main/java/org/sonarsource/sonarlint/ls/AnalysisHelper.java, src/main/java/org/sonarsource/sonarlint/ls/notebooks/VersionedOpenNotebook.java, src/test/java/org/sonarsource/sonarlint/ls/notebooks/VersionedOpenNotebookTests.java
[SLLS-265](https://sonarsource.atlassian.net/browse/SLLS-265)
[SLLS-265]: https://sonarsource.atlassian.net/browse/SLLS-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-265 fix Jupyter document line indexing

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java, src/main/java/org/sonarsource/sonarlint/ls/folders/WorkspaceFolderBranchManager.java, src/main/java/org/sonarsource/sonarlint/ls/util/GitUtils.java, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java, src/test/java/org/sonarsource/sonarlint/ls/folders/WorkspaceFolderBranchManagerTest.java, src/test/java/org/sonarsource/sonarlint/ls/util/GitUtilsTests.java, src/test/java/testutils/JavaUnzip.java
[SLLS-268](https://sonarsource.atlassian.net/browse/SLLS-268)
[SLLS-268]: https://sonarsource.atlassian.net/browse/SLLS-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-268 add possibility for backend to match with local branch

pom.xml
[SLLS-269](https://sonarsource.atlassian.net/browse/SLLS-269)
[SLLS-269]: https://sonarsource.atlassian.net/browse/SLLS-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-269 Prepare release 3.11.1

src/main/java/org/sonarsource/sonarlint/ls/LocalCodeFile.java
[SLLS-270](https://sonarsource.atlassian.net/browse/SLLS-270)
[SLLS-270]: https://sonarsource.atlassian.net/browse/SLLS-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-270 fix NullPointerException during ShowAllLocationsCommand

pom.xml
[SLLS-274](https://sonarsource.atlassian.net/browse/SLLS-274)
[SLLS-274]: https://sonarsource.atlassian.net/browse/SLLS-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-274 Bump to parent POM 80, remove unnecessary dependency

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/CommandManager.java, src/main/java/org/sonarsource/sonarlint/ls/EitherStandardOrMQRAdapterFactory.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageClient.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendService.java, src/main/java/org/sonarsource/sonarlint/ls/commands/ShowAllLocationsCommand.java, src/main/java/org/sonarsource/sonarlint/ls/domain/MQRModeDetails.java, src/main/java/org/sonarsource/sonarlint/ls/domain/StandardModeDetails.java, src/main/java/org/sonarsource/sonarlint/ls/domain/TaintIssue.java, src/main/java/org/sonarsource/sonarlint/ls/notebooks/DelegatingCellIssue.java, src/test/java/org/sonarsource/sonarlint/ls/CommandManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageClientTests.java, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java, src/test/java/org/sonarsource/sonarlint/ls/domain/TaintIssueTest.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerWithFoldersMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/notebooks/VersionedOpenNotebookTests.java
[SLLS-271](https://sonarsource.atlassian.net/browse/SLLS-271)
[SLLS-271]: https://sonarsource.atlassian.net/browse/SLLS-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-271 start using getIssueDetails method

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/Issue.java, src/main/java/org/sonarsource/sonarlint/ls/commands/ShowAllLocationsCommand.java, src/main/java/org/sonarsource/sonarlint/ls/connected/DelegatingFinding.java, src/test/java/org/sonarsource/sonarlint/ls/CommandManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/DiagnosticPublisherTests.java, src/test/java/org/sonarsource/sonarlint/ls/connected/DelegatingIssueTests.java, src/test/java/org/sonarsource/sonarlint/ls/connected/TaintVulnerabilitiesCacheTests.java, src/test/java/org/sonarsource/sonarlint/ls/notebooks/NotebookDiagnosticPublisherTests.java, src/test/java/org/sonarsource/sonarlint/ls/notebooks/VersionedOpenNotebookTests.java
[SLLS-275](https://sonarsource.atlassian.net/browse/SLLS-275)
Part of 
[SLLS-275]: https://sonarsource.atlassian.net/browse/SLLS-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-275 Stop using deprecated methods

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacade.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java
[SLLS-272](https://sonarsource.atlassian.net/browse/SLLS-272)
[SLLS-272]: https://sonarsource.atlassian.net/browse/SLLS-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-272 Adapt to C# analyzer repackaging

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/CommandManager.java, src/main/java/org/sonarsource/sonarlint/ls/DiagnosticPublisher.java, src/main/java/org/sonarsource/sonarlint/ls/SkippedPluginsNotifier.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendService.java, src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java, src/main/java/org/sonarsource/sonarlint/ls/connected/notifications/SmartNotifications.java, src/main/java/org/sonarsource/sonarlint/ls/domain/TaintIssue.java, src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java, src/test/java/org/sonarsource/sonarlint/ls/CommandManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/SkippedPluginsNotifierTests.java, src/test/java/org/sonarsource/sonarlint/ls/backend/BackendServiceTests.java, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java, src/test/java/org/sonarsource/sonarlint/ls/connected/notifications/SmartNotificationsTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/CFamilyMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/JavaMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerWithFoldersMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/NotebookMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/settings/SettingsManagerTests.java
[SLLS-276](https://sonarsource.atlassian.net/browse/SLLS-276)
[SLLS-276]: https://sonarsource.atlassian.net/browse/SLLS-276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-276 Update labels for SonarQube (Server, Cloud)

pom.xml
=> SLLS-278 Adapt to sonar-text repackaging

src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageClient.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerWithFoldersMediumTests.java
[SLLS-280](https://sonarsource.atlassian.net/browse/SLLS-280)
[SLLS-280]: https://sonarsource.atlassian.net/browse/SLLS-280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-280 exclude analysis of files not open in editor

src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java
[SLVSCODE-912](https://sonarsource.atlassian.net/browse/SLVSCODE-912)
[SLVSCODE-912]: https://sonarsource.atlassian.net/browse/SLVSCODE-912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-912 update docs links to match rebranding

pom.xml
[SLLS-282](https://sonarsource.atlassian.net/browse/SLLS-282)
Part of SLVSCODE-929
[SLLS-282]: https://sonarsource.atlassian.net/browse/SLLS-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-282 Update parent-pom

pom.xml
[SLLS-285](https://sonarsource.atlassian.net/browse/SLLS-285)
[SLLS-285]: https://sonarsource.atlassian.net/browse/SLLS-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-285 Prepare release 3.13

pom.xml
[SLLS-288](https://sonarsource.atlassian.net/browse/SLLS-288)
[SLLS-288]: https://sonarsource.atlassian.net/browse/SLLS-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-288 Prepare release 3.13.2

pom.xml
[SLLS-289](https://sonarsource.atlassian.net/browse/SLLS-289)
Part of  SLVSCODE-960
[SLLS-289]: https://sonarsource.atlassian.net/browse/SLLS-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-289 Use latest SLCORE

pom.xml
[SLLS-291](https://sonarsource.atlassian.net/browse/SLLS-291)
[SLLS-291]: https://sonarsource.atlassian.net/browse/SLLS-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-291 bearer auth fix

src/main/java/org/sonarsource/sonarlint/ls/EnabledLanguages.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java
[SLLS-290](https://sonarsource.atlassian.net/browse/SLLS-290)
[SLLS-290]: https://sonarsource.atlassian.net/browse/SLLS-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-290 support Ansible in Connected Mode

src/main/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacade.java, src/test/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacadeTests.java
[SLLS-294](https://sonarsource.atlassian.net/browse/SLLS-294)
Part of SLVSCODE-967
[SLLS-294]: https://sonarsource.atlassian.net/browse/SLLS-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-294 Fix QG by improving coverage

src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java
[SLVSCODE-846](https://sonarsource.atlassian.net/browse/SLVSCODE-846)
[SLVSCODE-846]: https://sonarsource.atlassian.net/browse/SLVSCODE-846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-846 stop using additionalAttributes map

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/CleanAsYouCodeManager.java, src/main/java/org/sonarsource/sonarlint/ls/DiagnosticPublisher.java, src/test/java/org/sonarsource/sonarlint/ls/CleanAsYouCodeManagerTest.java
[SLLS-295](https://sonarsource.atlassian.net/browse/SLLS-295)
[SLLS-295]: https://sonarsource.atlassian.net/browse/SLLS-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-295 republish all taints on CaYC toggle

pom.xml
[SLLS-297](https://sonarsource.atlassian.net/browse/SLLS-297)
[SLLS-297]: https://sonarsource.atlassian.net/browse/SLLS-297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-297 Use released sonarlint-core 10.13

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageClient.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendService.java, src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java, src/main/java/org/sonarsource/sonarlint/ls/connected/ProjectBindingManager.java, src/main/java/org/sonarsource/sonarlint/ls/domain/TaintIssue.java, src/main/java/org/sonarsource/sonarlint/ls/notebooks/DelegatingCellIssue.java, src/main/java/org/sonarsource/sonarlint/ls/settings/ServerConnectionSettings.java, src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java, src/main/java/org/sonarsource/sonarlint/ls/util/Utils.java, src/test/java/org/sonarsource/sonarlint/ls/CommandManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/backend/BackendServiceTests.java, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java, src/test/java/org/sonarsource/sonarlint/ls/connected/ProjectBindingManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/connected/api/HostInfoProviderTests.java, src/test/java/org/sonarsource/sonarlint/ls/domain/TaintIssueTest.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerWithFoldersMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/notebooks/VersionedOpenNotebookTests.java, src/test/java/org/sonarsource/sonarlint/ls/settings/ServerConnectionSettingsTests.java, src/test/java/org/sonarsource/sonarlint/ls/settings/SettingsManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/settings/WorkspaceSettingsTests.java, src/test/java/org/sonarsource/sonarlint/ls/util/UtilsTests.java
[SLLS-298](https://sonarsource.atlassian.net/browse/SLLS-298)
[SLLS-300](https://sonarsource.atlassian.net/browse/SLLS-300)
[SLLS-298]: https://sonarsource.atlassian.net/browse/SLLS-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLLS-300]: https://sonarsource.atlassian.net/browse/SLLS-300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-298 Update SLCORE version

src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java
[SLLS-301](https://sonarsource.atlassian.net/browse/SLLS-301)
SLLS-301
[SLLS-301]: https://sonarsource.atlassian.net/browse/SLLS-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-301 Include the new brand name in the User-Agent

pom.xml
[SLLS-305](https://sonarsource.atlassian.net/browse/SLLS-305)
[SLLS-305]: https://sonarsource.atlassian.net/browse/SLLS-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-305 SLLS- 304 Use released SLCORE

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/connected/ProjectBindingManager.java, src/main/java/org/sonarsource/sonarlint/ls/domain/TaintIssue.java, src/main/java/org/sonarsource/sonarlint/ls/notebooks/DelegatingCellIssue.java, src/main/java/org/sonarsource/sonarlint/ls/settings/EndpointParams.java, src/main/java/org/sonarsource/sonarlint/ls/settings/ServerConnectionSettings.java, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java, src/test/java/org/sonarsource/sonarlint/ls/domain/TaintIssueTest.java, src/test/java/org/sonarsource/sonarlint/ls/notebooks/DelegatingCellIssueTest.java, src/test/java/org/sonarsource/sonarlint/ls/notebooks/VersionedOpenNotebookTests.java
[SLLS-306](https://sonarsource.atlassian.net/browse/SLLS-306)
Part of SLVSCODE-1027
[SLLS-306]: https://sonarsource.atlassian.net/browse/SLLS-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-306 Update SLCORE version (git blaming improvements)

pom.xml, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/JavaMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java
[SLLS-308](https://sonarsource.atlassian.net/browse/SLLS-308)
[SLLS-308]: https://sonarsource.atlassian.net/browse/SLLS-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-308 Prepare release 3.17, use released SLCORE 10.16

.github/workflows/PullRequestClosed.yml
[SLLS-310](https://sonarsource.atlassian.net/browse/SLLS-310)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SLLS-310]: https://sonarsource.atlassian.net/browse/SLLS-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-310 Autoclose issues created by Jira integration

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/settings/ServerConnectionSettings.java, src/test/java/org/sonarsource/sonarlint/ls/backend/BackendServiceTests.java
[SLLS-311](https://sonarsource.atlassian.net/browse/SLLS-311)
[SLLS-311]: https://sonarsource.atlassian.net/browse/SLLS-311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-311 change US SonarQube Cloud URL

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/CommandManager.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacade.java, src/main/java/org/sonarsource/sonarlint/ls/settings/ServerConnectionSettings.java, src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerWithFoldersMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/settings/SettingsManagerTests.java
[SLLS-312](https://sonarsource.atlassian.net/browse/SLLS-312)
Part of SLVSCODE-1054
[SLLS-312]: https://sonarsource.atlassian.net/browse/SLLS-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-312 Pass alternative US region URLs to SLCORE

pom.xml
[SLLS-315](https://sonarsource.atlassian.net/browse/SLLS-315)
[SLLS-315]: https://sonarsource.atlassian.net/browse/SLLS-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-315 Use latest SLCORE

src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java
[SLLS-316](https://sonarsource.atlassian.net/browse/SLLS-316)
[SLLS-316]: https://sonarsource.atlassian.net/browse/SLLS-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-316 Close files that do not belong to a workspace folder

pom.xml
[SLLS-317](https://sonarsource.atlassian.net/browse/SLLS-317)
Part of SLVSCODE-1103
[SLLS-317]: https://sonarsource.atlassian.net/browse/SLLS-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-317 Prepare release 3.19

src/main/java/org/sonarsource/sonarlint/ls/CommandManager.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageClient.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendService.java, src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java, src/main/java/org/sonarsource/sonarlint/ls/domain/TaintIssue.java, src/main/java/org/sonarsource/sonarlint/ls/notebooks/OpenNotebooksCache.java, src/test/java/org/sonarsource/sonarlint/ls/CommandManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/backend/BackendServiceTests.java, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/NotebookMediumTests.java
[SLLS-313](https://sonarsource.atlassian.net/browse/SLLS-313)
[SLLS-313]: https://sonarsource.atlassian.net/browse/SLLS-313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-313 provide Fix with AI CodeFix Code Action

pom.xml, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/JavaMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerWithFoldersMediumTests.java
[SLLS-323](https://sonarsource.atlassian.net/browse/SLLS-323)
[SLLS-323]: https://sonarsource.atlassian.net/browse/SLLS-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-323 Update to the latest SLCORE

pom.xml
[SLLS-326](https://sonarsource.atlassian.net/browse/SLLS-326)
[SLLS-326]: https://sonarsource.atlassian.net/browse/SLLS-326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-326 Update to the latest SLCORE

pom.xml
[SLLS-326](https://sonarsource.atlassian.net/browse/SLLS-326)
[SLLS-326]: https://sonarsource.atlassian.net/browse/SLLS-326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-326 Prepare bugfix release

src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java
[SLLS-328](https://sonarsource.atlassian.net/browse/SLLS-328)
[SLLS-328]: https://sonarsource.atlassian.net/browse/SLLS-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-328 remove didReceiveHotspotEvent method

pom.xml
[SLLS-332](https://sonarsource.atlassian.net/browse/SLLS-332)
[SLLS-332]: https://sonarsource.atlassian.net/browse/SLLS-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-332 Prepare next dev iteration

src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendInitParams.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacade.java, src/test/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacadeTests.java
[SLLS-331](https://sonarsource.atlassian.net/browse/SLLS-331)
Part of SLVSCODE-1099
[SLLS-331]: https://sonarsource.atlassian.net/browse/SLLS-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-331 Stop relying on FeatureFlagsDto

pom.xml
[SLLS-335](https://sonarsource.atlassian.net/browse/SLLS-335)
[SLLS-335]: https://sonarsource.atlassian.net/browse/SLLS-335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-335 Update to SLCORE 10.21

src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java
[SLVSCODE-1164](https://sonarsource.atlassian.net/browse/SLVSCODE-1164)
[SLVSCODE-1164]: https://sonarsource.atlassian.net/browse/SLVSCODE-1164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1164 request SonarQube Cloud tokens with correct key

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java
[SLLS-333](https://sonarsource.atlassian.net/browse/SLLS-333)
SLLS-333
[SLLS-333]: https://sonarsource.atlassian.net/browse/SLLS-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-333 Update SLCORE to use synchronized Go analyzer with SQS 2025.2+

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendService.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java
[SLLS-339](https://sonarsource.atlassian.net/browse/SLLS-339)
[SLLS-339]: https://sonarsource.atlassian.net/browse/SLLS-339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-339 get connection suggestions from backend

src/main/java/org/sonarsource/sonarlint/ls/backend/BackendService.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java
[SLLS-341](https://sonarsource.atlassian.net/browse/SLLS-341)
This is just a temporary fix until SLLS-340 is implemented
[SLLS-341]: https://sonarsource.atlassian.net/browse/SLLS-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-341 Fix coverage

pom.xml
[SLLS-299](https://sonarsource.atlassian.net/browse/SLLS-299)
[SLLS-299]: https://sonarsource.atlassian.net/browse/SLLS-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-299 Drop commons-io

src/main/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacade.java
[SLLS-320](https://sonarsource.atlassian.net/browse/SLLS-320)
=> SLLS-320 Fix NPE on user home path at initialization

src/main/java/org/sonarsource/sonarlint/ls/CommandManager.java, src/main/java/org/sonarsource/sonarlint/ls/DiagnosticPublisher.java, src/main/java/org/sonarsource/sonarlint/ls/connected/TaintVulnerabilitiesCache.java, src/test/java/org/sonarsource/sonarlint/ls/CommandManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/DiagnosticPublisherTests.java, src/test/java/org/sonarsource/sonarlint/ls/connected/TaintVulnerabilitiesCacheTests.java
[SLLS-349](https://sonarsource.atlassian.net/browse/SLLS-349)
Part of MMF-4619
[SLLS-349]: https://sonarsource.atlassian.net/browse/SLLS-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-349 Send Taint ServerIssueKey to client

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/telemetry/SonarLintTelemetry.java, src/test/java/org/sonarsource/sonarlint/ls/telemetry/SonarLintTelemetryTests.java
[SLLS-350](https://sonarsource.atlassian.net/browse/SLLS-350)
[SLLS-350]: https://sonarsource.atlassian.net/browse/SLLS-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-350 Use new telemetry for taint investigation

pom.xml
[SLLS-352](https://sonarsource.atlassian.net/browse/SLLS-352)
=> SLLS-352 Prepare next dev iteration

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacade.java, src/test/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacadeTests.java
[SLLS-353](https://sonarsource.atlassian.net/browse/SLLS-353)
[SLLS-353]: https://sonarsource.atlassian.net/browse/SLLS-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-353 Update to latest SLCORE

pom.xml
[SLLS-357](https://sonarsource.atlassian.net/browse/SLLS-357)
Part of SLVSCODE-1224
[SLLS-357]: https://sonarsource.atlassian.net/browse/SLLS-357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-357 Use released SLCORE

pom.xml
[SLLS-358](https://sonarsource.atlassian.net/browse/SLLS-358)
[SLLS-358]: https://sonarsource.atlassian.net/browse/SLLS-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-358 Prepare next dev iteration

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/CommandManager.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/telemetry/SonarLintTelemetry.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/telemetry/SonarLintTelemetryTests.java
[SLLS-356](https://sonarsource.atlassian.net/browse/SLLS-356)
Part of 
[SLLS-356]: https://sonarsource.atlassian.net/browse/SLLS-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-356 Telemetry for filters and issues investigated

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/CommandManager.java, src/main/java/org/sonarsource/sonarlint/ls/DiagnosticPublisher.java, src/main/java/org/sonarsource/sonarlint/ls/IssuesCache.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/connected/TaintVulnerabilitiesCache.java, src/main/java/org/sonarsource/sonarlint/ls/telemetry/SonarLintTelemetry.java, src/test/java/org/sonarsource/sonarlint/ls/CommandManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/DiagnosticPublisherTests.java, src/test/java/org/sonarsource/sonarlint/ls/IssuesCacheTest.java, src/test/java/org/sonarsource/sonarlint/ls/connected/TaintVulnerabilitiesCacheTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/notebooks/NotebookDiagnosticPublisherTests.java, src/test/java/org/sonarsource/sonarlint/ls/telemetry/SonarLintTelemetryTests.java
[SLVSCODE-1226](https://sonarsource.atlassian.net/browse/SLVSCODE-1226)
[SLVSCODE-1226]: https://sonarsource.atlassian.net/browse/SLVSCODE-1226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1226 differentiate local hotspots and issues; show all flows for an issue

src/main/java/org/sonarsource/sonarlint/ls/commands/ShowAllLocationsCommand.java
[SLVSCODE-1282](https://sonarsource.atlassian.net/browse/SLVSCODE-1282)
[SLVSCODE-1282]: https://sonarsource.atlassian.net/browse/SLVSCODE-1282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-1282 findings view improvements

pom.xml
[SLLS-360](https://sonarsource.atlassian.net/browse/SLLS-360)
Part of SLVSCODE-1246
[SLLS-360]: https://sonarsource.atlassian.net/browse/SLLS-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-360 Prepare release 3.27

src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendService.java, src/main/java/org/sonarsource/sonarlint/ls/connected/DependencyRisksCache.java, src/test/java/org/sonarsource/sonarlint/ls/backend/BackendServiceTests.java, src/test/java/org/sonarsource/sonarlint/ls/connected/DependencyRisksCacheTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java
[SLLS-362](https://sonarsource.atlassian.net/browse/SLLS-362)
[SLLS-362]: https://sonarsource.atlassian.net/browse/SLLS-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-362 allow changing dependency risk status

src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java, src/main/java/org/sonarsource/sonarlint/ls/settings/WorkspaceSettings.java, src/test/java/org/sonarsource/sonarlint/ls/CleanAsYouCodeManagerTest.java, src/test/java/org/sonarsource/sonarlint/ls/connected/ProjectBindingManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/log/LanguageClientLoggerTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/JavaMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/settings/SettingsManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/settings/WorkspaceSettingsTests.java, src/test/java/org/sonarsource/sonarlint/ls/telemetry/SonarLintTelemetryTests.java
[SLLS-369](https://sonarsource.atlassian.net/browse/SLLS-369)
[SLLS-369]: https://sonarsource.atlassian.net/browse/SLLS-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-369 remove showAnalyzerLogs setting

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/EnabledLanguages.java, src/main/java/org/sonarsource/sonarlint/ls/domain/DependencyRisk.java, src/main/java/org/sonarsource/sonarlint/ls/domain/LSLanguage.java, src/test/java/org/sonarsource/sonarlint/ls/domain/LSLanguageTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java
[SLLS-371](https://sonarsource.atlassian.net/browse/SLLS-371)
[SLLS-371]: https://sonarsource.atlassian.net/browse/SLLS-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-371 Declare support for GitHub Actions in connected mode

src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServerInitializationOptions.java, src/main/java/org/sonarsource/sonarlint/ls/settings/RulesConfiguration.java, src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/settings/SettingsManagerTests.java
[SLLS-377](https://sonarsource.atlassian.net/browse/SLLS-377)
[SLLS-377]: https://sonarsource.atlassian.net/browse/SLLS-377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-377 Refactor parsing of initialization options

.cirrus.yml
[SLLS-382](https://sonarsource.atlassian.net/browse/SLLS-382)
[SLLS-382]: https://sonarsource.atlassian.net/browse/SLLS-382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-382 Increase CPU for qa_windows task

pom.xml, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java
[SLLS-383](https://sonarsource.atlassian.net/browse/SLLS-383)
[SLLS-383]: https://sonarsource.atlassian.net/browse/SLLS-383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-383 Prepare release 4.0

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageClient.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendService.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacade.java, src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java, src/main/java/org/sonarsource/sonarlint/ls/flightrecorder/FlightRecorderManager.java, src/main/java/org/sonarsource/sonarlint/ls/flightrecorder/package-info.java, src/test/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacadeTests.java, src/test/java/org/sonarsource/sonarlint/ls/backend/BackendServiceTests.java, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java, src/test/java/org/sonarsource/sonarlint/ls/flightrecorder/FlightRecorderManagerTest.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java
[SLLS-386](https://sonarsource.atlassian.net/browse/SLLS-386)
[SLLS-386]: https://sonarsource.atlassian.net/browse/SLLS-386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-386 Support flight recorder mode

pom.xml, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java
[SLLS-389](https://sonarsource.atlassian.net/browse/SLLS-389)
[SLLS-389]: https://sonarsource.atlassian.net/browse/SLLS-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-389 Use released SLCORE 10.31

.github/workflows/shadow-scans.yml
[SLLS-387](https://sonarsource.atlassian.net/jira/software/c/projects/SLCORE/boards/1527?selectedIssue=SLLS-387)
[SLLS-387]: https://sonarsource.atlassian.net/browse/SLLS-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-387 Fix Shadow Scans

src/main/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacade.java, src/test/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacadeTests.java
[SLLS-398](https://sonarsource.atlassian.net/browse/SLLS-398)
[SLLS-398]: https://sonarsource.atlassian.net/browse/SLLS-398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-398 Collect usage data separately for Cursor and Windsurf

src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServerInitializationOptions.java
[SLLS-401](https://sonarsource.atlassian.net/browse/SLLS-401)
Copy of #532 
[SLLS-401]: https://sonarsource.atlassian.net/browse/SLLS-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-401 Don't Rely on LSP Client to Init Maps
