src/main/java/org/sonarsource/sonarlint/ls/AnalysisManager.java, src/main/java/org/sonarsource/sonarlint/ls/CommandManager.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageClient.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintTelemetry.java, src/main/java/org/sonarsource/sonarlint/ls/Utils.java, src/main/java/org/sonarsource/sonarlint/ls/commands/ShowAllLocationsCommand.java, src/main/java/org/sonarsource/sonarlint/ls/connected/ProjectBindingManager.java, src/test/java/org/sonarsource/sonarlint/ls/AnalysisManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/CommandManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/SonarLintTelemetryTests.java, src/test/java/org/sonarsource/sonarlint/ls/UtilsTest.java, src/test/java/org/sonarsource/sonarlint/ls/commands/ShowAllLocationsCommandTest.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/JavaMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java
This PR contains several changes:
- one new feature (code action to open a taint vulnerability in the browser)
- one missed feature (telemetry about taint vulnerabilities investigated locally)
- PM feedback from rounds of demos
=> SLLS-23 Code action to investigate taint vulnerability on the originating server

src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java
This change was a side effect of the refactoring from fe89708 and caused this exception:
```text
[Error - 17:14:08.242] Error starting connected SonarLint engine for 'SQDev9.9'
[Error - 17:14:08.243] java.lang.IllegalStateException: Duplicate plugin key 'cpp' from '/home/jean-baptistelievremont/.vscode/extensions/sonarsource.sonarlint-vscode-3.15.0+61639/analyzers/sonarcfamily.jar' and '/home/jean-baptistelievremont/.sonarlint/storage/5351446576392e39/plugins/sonar-cfamily-plugin-6.41.0.60884.jar'
at org.sonarsource.sonarlint.core.plugin.commons.loading.SonarPluginRequirementsChecker.checkRequirements(SonarPluginRequirementsChecker.java:74)
at org.sonarsource.sonarlint.core.plugin.commons.PluginsLoader.load(PluginsLoader.java:71)
at …
```
=> SLVSCODE-406 Fix plugin key for embedded CFamily plugin

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/ServerMain.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/test/java/org/sonarsource/sonarlint/ls/ServerMainTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java
This PR adds support for serving the language over stdio channel which is the default communication channel in tools such as Neovim. That use case has been also reported in the forum (see [here](https://community.sonarsource.com/t/running-sonarlint-language-server-from-shell/24440/14)).
The changes include but are still work in progress: 
- Use picocli to improve CLI parsing
- Start language server via stdio channeling
- Avoid NPE if client doesn't send initialize params
The language server works with Neovim (started with `java -jar /path/to/sonarlint-language-server/target/sonarlint-language-server-2.14.0-SNAPSHOT.jar -stdio -analyzers ~/Downloads/sonar/extension/analyzers/sonarjava.jar` and shown by `:LspInfo`, shown in the screencast) but there are no reports.
I have some lua stubs in …
=> Implement Stdio Channel

azure-pipelines.yml, pom.xml, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageClient.java, src/main/java/org/sonarsource/sonarlint/ls/connected/notifications/ServerNotifications.java, src/test/java/org/sonarsource/sonarlint/ls/connected/notifications/ServerNotificationsTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerWithFoldersMediumTests.java
**Stabilize tests**
- Replace JS analyzer with Python analyzer where appropriate.
- Add 'readyForTests' notification to notify tests about readiness.
**Stabilize/Improve builds**
- Run builds with different Java versions. Linux is run with v11, and Windows with v17.
- Update analyzers to versions used by SonarLint in production or newer.
=> Stabilize tests

src/test/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageClientTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/JavaMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java
There were some leftover tests in LanguageServerMediumTests and JavaMediumTests that could have been switched to use python analyzers. It was done in this branch.
=>  Replace JS with Python in connected mode tests  - Part II

src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/JavaMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerWithFoldersMediumTests.java
Fix `@TempDir` directory cannot be deleted ([ConnectedModeMediumTests IO Failed to delete temp directory](https://dev.azure.com/sonarsource/DotNetTeam%20Project/_build/results?buildId=64605&view=logs&j=81cabcdf-75d9-5672-240e-9040d2927080&s=3df7d716-4c9c-5c26-9f45-11f62216640d&t=1b57360e-bdec-515f-6474-56e699defbf8&l=2351)) by creating and deleting temp dir manually. 
Currently done only for ConnectedModeMediumTests as that's where the issue is observed.
=> Fix @TempDir directory cannot be deleted 

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/CommandManager.java, src/main/java/org/sonarsource/sonarlint/ls/DiagnosticPublisher.java, src/main/java/org/sonarsource/sonarlint/ls/IssuesCache.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendService.java, src/main/java/org/sonarsource/sonarlint/ls/connected/TaintVulnerabilitiesCache.java, src/main/java/org/sonarsource/sonarlint/ls/http/ApacheHttpClient.java, src/test/java/org/sonarsource/sonarlint/ls/CommandManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/connected/TaintVulnerabilitiesCacheTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java, src/test/java/testutils/MockWebServerExtension.java
- Add Code Action to an issue (applicable for both taint issues and regular issues)
- When the client requests muting an issue, forward the data to an appropriate handler from SLCORE
=> SLLS-152    Add method to pass IssueStatus and Comment to SLCORE

pom.xml, src/test/java/org/sonarsource/sonarlint/ls/folders/WorkspaceFolderBranchManagerTests.java
update org.eclipse.jgit 6.4.0.202211300538-r --> 6.5.0.202303070854-r
Looks like we use jgit only in tests so updating it should be safe enough change
=> SLLS-160 update org.eclipse.jgit to 6.5.0.202303070854-r

.cirrus.yml
The qa_linux_task relies on regular_mvn_build_deploy_analyze to avoid complex setup and duplication.
It fails on master complaining on missing variables, because the script behavior is different on master than on PR:
- `deploy` phase is called instead of verify.
- `deploy-sonarsource`, `release` and `sign` profiles are activated
Solution:
- explicit call of `verify` phase. Not required but useful for the sake and clarity.
- skip execution of maven-install-plugin and maven-deploy-plugin
- deactivate `deploy-sonarsource`, `release` and `sign` profiles
=> BUILD-3062 fix master build

.cirrus.yml
Circumvent BUILD-3169 (ws_scan.sh overrides product names from wss-unified-agent.config
=> BUILD-3062 fix Mend product name

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/CommandManager.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendService.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacade.java, src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java, src/main/java/org/sonarsource/sonarlint/ls/connected/api/RequestsHandlerServer.java, src/test/java/org/sonarsource/sonarlint/ls/CommandManagerTests.java, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java
The context action to mark an issue as Won’t Fix or False Positive is currently named “Resolve this issue violating rule 'XXX'“ 
Some user research revealed that this naming does not work well with users, and especially it leads them to think that activating this action will directly change the issue’s status: https://www.figma.com/file/zh6eXTtgtiLY7S68dRmETX/Open-issues-from-SC%2FSQ-to-IDE?type=whiteboard&node-id=0-1&t=6OqGvavCR2L8Hgcd-0 - Connect your Figma account 
I propose to rename the action “Mark issue violating rule 'XXX' as…“ similarly to what is already done in SLE
=> SLLS-169 Improve name for 'Mark as Resolved' action

src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java
Turned out that in the previous implementation, we were never actually cleaning up the `WorkspaceFoldersManager` folder cache.
So after this rework `AbstractLanguageServerMediumTests.closeFiles()` doing this properly.
=> SLLS-227 Remove temporary workaround endpoints for config scopes

.cirrus/slack-notification.sh
The task name is now displayed instead of the id. Additionally the branch name is now more prominent.
=> SLLS-223: Reworked the Slack notification

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacade.java, src/main/java/org/sonarsource/sonarlint/ls/telemetry/SonarLintTelemetry.java
Note: this commit also has an updated core that should log details about why a configuration scope is not available for analysis.
=> SLLS-229 Move telemetry kill switch system property from core to language server

src/main/java/org/sonarsource/sonarlint/ls/folders/WorkspaceFoldersManager.java
Since the URI can contain %-encoded characters, some end up clashing with string format sequences. At this point, an exception is thrown and the folder nevers becomes ready.
=> SLVSCODE-729 Replace string concatenation with message formatting in log

src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java
The signature of `SslCertificateConfirmationParams` asks for `validFrom` and then `validTo`.
https://github.com/SonarSource/sonarlint-language-server/blob/675fb6944239e1c581c1494fa162d4ea90c4bb80/src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageClient.java#L837-L838
When the VS Code client is prompting to trust an untrusted certificate, it's providing the parameters in the wrong order, `notAfter` (which should map to `validTo`), then `notBefore` (which should map to `validFrom`).
https://github.com/SonarSource/sonarlint-language-server/blob/675fb6944239e1c581c1494fa162d4ea90c4bb80/src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java#L369-L370
As a result, the prompt reports a certificate that should not possibly exist, with a `validTo` after …
=> SLLS-235 Fix swapped certificate dates when prompting about untrusted certificate

src/main/java/org/sonarsource/sonarlint/ls/notebooks/VersionedOpenNotebook.java
[SLLS-265](https://sonarsource.atlassian.net/browse/SLLS-265)
[SLLS-265]: https://sonarsource.atlassian.net/browse/SLLS-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-265 fix QG

src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java, src/test/java/org/sonarsource/sonarlint/ls/settings/SettingsManagerTests.java
[SLLS-266](https://sonarsource.atlassian.net/browse/SLLS-266)
[SLLS-266]: https://sonarsource.atlassian.net/browse/SLLS-266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-266 correctly handle JSON values in settings

src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java
[SLLS-207](https://sonarsource.atlassian.net/browse/SLLS-207)
[SLLS-207]: https://sonarsource.atlassian.net/browse/SLLS-207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-207 do not notify backend after assistCreatingConnection

.cirrus.star, .cirrus.yml
[SLLS-273](https://sonarsource.atlassian.net/browse/SLLS-273)
1. Update cirrus-module v2 to v3.
2. Do not call the deprecated AWS feature method parameters `subnet_id`.
3. It is recommended to not use `ec2_instance` or `eks_container` root keys.
[SLLS-273]: https://sonarsource.atlassian.net/browse/SLLS-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-273 Migrate deprecated cirrus-module v2 to v3

src/main/java/org/sonarsource/sonarlint/ls/ServerMain.java, src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java, src/test/java/org/sonarsource/sonarlint/ls/ServerMainTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java
[SLLS-277](https://sonarsource.atlassian.net/browse/SLLS-277)
Internal copy of #402 to let CI checks run
[SLLS-277]: https://sonarsource.atlassian.net/browse/SLLS-277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-277 Fix JsonNull conversion error

src/main/java/org/sonarsource/sonarlint/ls/java/JavaConfigCache.java
[SLLS-279](https://sonarsource.atlassian.net/browse/SLLS-279)
[SLLS-279]: https://sonarsource.atlassian.net/browse/SLLS-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-279 populate sonar.java.source analyzer property when possible

src/main/java/org/sonarsource/sonarlint/ls/settings/RulesConfiguration.java, src/test/java/org/sonarsource/sonarlint/ls/settings/RulesConfigurationTests.java
[SLVSCODE-895](https://sonarsource.atlassian.net/browse/SLVSCODE-895)
[SLVSCODE-895]: https://sonarsource.atlassian.net/browse/SLVSCODE-895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-895 if level not specified, turn the rule ON

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendService.java, src/main/java/org/sonarsource/sonarlint/ls/folders/ModuleEventsProcessor.java, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java, src/test/java/org/sonarsource/sonarlint/ls/commands/ShowAllLocationsCommandTests.java, src/test/java/org/sonarsource/sonarlint/ls/folders/ModuleEventsProcessorTest.java
[SLLS-281](https://sonarsource.atlassian.net/browse/SLLS-281)
[SLLS-281]: https://sonarsource.atlassian.net/browse/SLLS-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-281 distinguish added and modified files

src/main/java/org/sonarsource/sonarlint/ls/AnalysisHelper.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintLanguageServer.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendService.java, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacade.java, src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java, src/main/java/org/sonarsource/sonarlint/ls/folders/ModuleEventsProcessor.java, src/main/java/org/sonarsource/sonarlint/ls/settings/SettingsManager.java, src/test/java/org/sonarsource/sonarlint/ls/backend/BackendServiceTests.java, src/test/java/org/sonarsource/sonarlint/ls/folders/ModuleEventsProcessorTest.java, src/test/java/org/sonarsource/sonarlint/ls/folders/WorkspaceFoldersManagerTests.java
[SLLS-286](https://sonarsource.atlassian.net/browse/SLLS-286)
[SLLS-286]: https://sonarsource.atlassian.net/browse/SLLS-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-286 Fix cycle between classes

pom.xml, src/main/java/org/sonarsource/sonarlint/ls/backend/BackendServiceFacade.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java
[SLLS-283](https://sonarsource.atlassian.net/browse/SLLS-283)
SLLS-283
[SLLS-283]: https://sonarsource.atlassian.net/browse/SLLS-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-283 Use monitoring facility from core backend

pom.xml, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/JavaMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/LanguageServerMediumTests.java
[SLLS-292](https://sonarsource.atlassian.net/browse/SLLS-292)
[SLLS-292]: https://sonarsource.atlassian.net/browse/SLLS-292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLLS-292 use latest analyzers

src/main/java/org/sonarsource/sonarlint/ls/DiagnosticPublisher.java, src/main/java/org/sonarsource/sonarlint/ls/SonarLintExtendedLanguageClient.java, src/main/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClient.java, src/test/java/org/sonarsource/sonarlint/ls/clientapi/SonarLintVSCodeClientTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/AbstractLanguageServerMediumTests.java, src/test/java/org/sonarsource/sonarlint/ls/mediumtests/ConnectedModeMediumTests.java
[SLVSCODE-966](https://sonarsource.atlassian.net/browse/SLVSCODE-966)
[SLVSCODE-966]: https://sonarsource.atlassian.net/browse/SLVSCODE-966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLVSCODE-966 publish taints notification
